//
// Milkyway Hierarchical Verilog Dump:
// Generated on 08/10/2018 at 10:04:11
// Design Generated by Consolidated Verilog Reader
// File produced by Consolidated Verilog Writer
// Library Name :JOHNSON.mw
// Cell Name    :johnson
// Hierarchy delimiter:'/'
// Write Command : write_verilog -pg -no_physical_only_cells ../results/johnson_icc.v
//


module johnson (out , VDD , VSS , SCANOUTPORT , r , clk , SE , 
    SCANINPORT );
output [0:7] out ;
inout  VDD ;
inout  VSS ;
output SCANOUTPORT ;
input  r ;
input  clk ;
input  SE ;
input  SCANINPORT ;

supply1 VDD ;
supply0 VSS ;


SAEDRVT14_BUF_S_1 U12 (.VSS ( VSS ) , .VDD ( VDD ) , .A ( out[5] ) , .X ( n23 ) ) ;
SAEDRVT14_BUF_S_1 U11 (.VSS ( VSS ) , .VDD ( VDD ) , .A ( out[4] ) , .X ( n22 ) ) ;
SAEDRVT14_BUF_ECO_1 U9 (.VDD ( VDD ) , .VSS ( VSS ) , .A ( n22 ) , .X ( n21 ) ) ;
SAEDRVT14_BUF_S_1 U8 (.VSS ( VSS ) , .VDD ( VDD ) , .A ( out[3] ) , .X ( n20 ) ) ;
SAEDRVT14_BUF_S_1 U7 (.VSS ( VSS ) , .VDD ( VDD ) , .A ( out[2] ) , .X ( n19 ) ) ;
SAEDRVT14_BUF_S_1 U6 (.VSS ( VSS ) , .VDD ( VDD ) , .A ( out[1] ) , .X ( n18 ) ) ;
SAEDRVT14_BUF_S_1 U5 (.VSS ( VSS ) , .VDD ( VDD ) , .A ( out[0] ) , .X ( n17 ) ) ;
SAEDRVT14_BUF_S_1 U4 (.VSS ( VSS ) , .VDD ( VDD ) , .A ( n10 ) , .X ( n16 ) ) ;
SAEDRVT14_BUF_S_1 U3 (.VSS ( VSS ) , .VDD ( VDD ) , .A ( out[6] ) , .X ( n15 ) ) ;
SAEDRVT14_BUF_ECO_1 U2 (.VDD ( VDD ) , .VSS ( VSS ) , .A ( n15 ) , .X ( n14 ) ) ;
SAEDRVT14_INV_S_12 SAEDRVT14_INV_S_20_BC_1 (.VSS ( VSS ) , .VDD ( VDD ) 
    , .A ( clk_BC ) , .X ( clk_BC_1 ) ) ;
SAEDRVT14_INV_S_20 SAEDRVT14_INV_S_20_BC (.VSS ( VSS ) , .VDD ( VDD ) 
    , .A ( clk ) , .X ( clk_BC ) ) ;
SAEDRVT14_BUF_ECO_1 U1 (.VDD ( VDD ) , .VSS ( VSS ) , .A ( out[7] ) 
    , .X ( SCANOUTPORT ) ) ;
SAEDRVT14_FSDPRBQ_V2_0P5 \out_reg[7] (.VSS ( VSS ) , .VDD ( VDD ) 
    , .Q ( out[7] ) , .SE ( SE ) , .D ( n14 ) , .SI ( n15 ) , .CK ( clk_BC_1 ) 
    , .RD ( n8 ) ) ;
SAEDRVT14_FSDPRBQ_V2_0P5 \out_reg[0] (.VSS ( VSS ) , .VDD ( VDD ) 
    , .Q ( out[0] ) , .SE ( SE ) , .D ( n16 ) , .SI ( SCANINPORT ) 
    , .CK ( clk_BC_1 ) , .RD ( n8 ) ) ;
SAEDRVT14_FSDPRBQ_V2_0P5 \out_reg[1] (.VSS ( VSS ) , .VDD ( VDD ) 
    , .Q ( out[1] ) , .SE ( SE ) , .D ( n17 ) , .SI ( n17 ) , .CK ( clk_BC_1 ) 
    , .RD ( n8 ) ) ;
SAEDRVT14_FSDPRBQ_V2_0P5 \out_reg[2] (.VSS ( VSS ) , .VDD ( VDD ) 
    , .Q ( out[2] ) , .SE ( SE ) , .D ( n18 ) , .SI ( n18 ) , .CK ( clk_BC_1 ) 
    , .RD ( n8 ) ) ;
SAEDRVT14_FSDPRBQ_V2_0P5 \out_reg[3] (.VSS ( VSS ) , .VDD ( VDD ) 
    , .Q ( out[3] ) , .SE ( SE ) , .D ( n19 ) , .SI ( n19 ) , .CK ( clk_BC_1 ) 
    , .RD ( n8 ) ) ;
SAEDRVT14_FSDPRBQ_V2_0P5 \out_reg[4] (.VSS ( VSS ) , .VDD ( VDD ) 
    , .Q ( out[4] ) , .SE ( SE ) , .D ( n20 ) , .SI ( n20 ) , .CK ( clk_BC_1 ) 
    , .RD ( n8 ) ) ;
SAEDRVT14_FSDPRBQ_V2_0P5 \out_reg[5] (.VSS ( VSS ) , .VDD ( VDD ) 
    , .Q ( out[5] ) , .SE ( SE ) , .D ( n21 ) , .SI ( n22 ) , .CK ( clk_BC_1 ) 
    , .RD ( n8 ) ) ;
SAEDRVT14_FSDPRBQ_V2_0P5 \out_reg[6] (.VSS ( VSS ) , .VDD ( VDD ) 
    , .Q ( out[6] ) , .SE ( SE ) , .D ( n23 ) , .SI ( n23 ) , .CK ( clk_BC_1 ) 
    , .RD ( n8 ) ) ;
SAEDRVT14_INV_S_0P75 U10 (.VDD ( VDD ) , .VSS ( VSS ) , .A ( r ) , .X ( n8 ) ) ;
SAEDRVT14_INV_1 U14 (.VSS ( VSS ) , .VDD ( VDD ) , .X ( n10 ) , .A ( out[7] ) ) ;
endmodule


